### ISSUE TITLE
Extra, Nonexistent Space Displayed 

### ISSUE THREAD

**Issue by jetblackrx89** [Jaysce/Spaceman#8] opened 2021-05-02 19:40 UTC
An extra, nonexistent space is displayed to the left of the actual, available spaces. See attached photo. "Screen 1" does not exist.

<img width="125" alt="Screen Shot 2021-05-02 at 3 39 06 PM" src="https://user-images.githubusercontent.com/7515801/116825300-a7790800-ab5c-11eb-801e-275bd872b5fb.png">

<img width="2559" alt="Screen Shot 2021-05-02 at 3 38 44 PM" src="https://user-images.githubusercontent.com/7515801/116825305-ab0c8f00-ab5c-11eb-8c2d-780fc414c82d.png">

**Comment by Jaysce** [comment] 2021-05-03 03:41
Is this persistent even after a refresh or switching to a different space? Is there a way to reproduce this or has it been like this since you installed the app?

**Comment by jetblackrx89** [comment] 2021-05-03 04:09
Thanks for the reply. It's been like this since I've installed the app. I don't know if it's because of Sidecar or something. Yes, it persists even when switching between spaces. What's weird is if a boot off a clean Big Sur installation, the issue isn't seen.

**Comment by Jaysce** [comment] 2021-05-05 07:32
### If you installed using Homebrew, could you try running the following in terminal:
1. `defaults delete dev.jaysce.Spaceman`
2. `brew uninstall --zap spaceman`
3.  and then installing again, `brew install spaceman`.

### Or If you installed through GitHub, run the following:
1. `defaults delete dev.jaysce.Spaceman`

**If you have AppCleaner installed, use that to uninstall Spaceman then reinstall, otherwise run the following in terminal:**

2. `rm -rf ~/Library/Application\ Scripts/dev.jaysce.Spaceman-LaunchAtLoginHelper`
3. `rm -rf ~/Library/Caches/dev.jaysce.Spaceman`
4. `rm -rf ~/Library/Containers/dev.jaysce.Spaceman-LaunchAtLoginHelper`
5. `rm -rf ~/Library/Preferences/dev.jaysce.Spaceman.plist`
6. Then delete Spaceman.app by moving to bin and emptying the bin
7. Reinstall Spaceman through GitHub or Homebrew

Let me know if that helps.

**Comment by jetblackrx89** [comment] 2021-05-05 13:44
Thanks. Unfortunately, none of that helped. I previously tried to uninstall it using CleanMyMac but also did it via your instructions just now.

**Comment by Jaysce** [comment] 2021-05-05 17:21
Maybe try this:
1. Quit Spaceman.app
2. Run `rm -rf ~/Library/Preferences/com.apple.spaces.plist` in terminal.
3. Create a new Space
4. Open Spaceman.app

**Comment by jetblackrx89** [comment] 2021-05-05 18:19
Thanks. So deleting "com.apple.spaces.plist" in terminal and rebooting my Mac fixed the issue.

One really bizarre thing is that when my computer came back up, obviously it only had 1 space, but it was using a really old wallpaper from years ago. It's almost as if macOS was retaining some data about an old space that was hidden this entire time from view. I am still wondering if this is a leftover from back when macOS supported Dashboard, which used to count as a "space" as well.

**Comment by Jaysce** [comment] 2021-05-05 18:31
Yea I'm pretty sure Dashboard was the problem. When Dashboard was supported it also counted as a space, and I guess it's left over in that plist even after updating the OS.

Glad the bug is fixed!

**Closed by Jaysce** 2021-05-05 18:31 UTC
Labels: bug
